package skiclient;

import java.util.concurrent.BlockingDeque;
import java.util.concurrent.BlockingQueue;

public class RecordUploader extends Thread {
/*
multi-thread uploader to upload random events that generated by EventGenerator to the server
 */
    private RecordUploadClient recordUploadClient;
    private BlockingQueue<UploadEvent> queue;
    private BlockingQueue<Integer> outputQueue;
    private int limit;

    public RecordUploader(RecordUploadClient recordUploadClient, BlockingQueue<UploadEvent> queue, int limit, BlockingQueue<Integer> outputQueue) {
        this.recordUploadClient = recordUploadClient;
        this.queue = queue;
        this.limit = limit;
        this.outputQueue = outputQueue;
    }

    @Override
    public void run() {
        try {
            if (limit > 0) {
                for (int i = 0; i < limit; i++) {
                    UploadEvent uploadEvent = queue.take();
                    Integer result = recordUploadClient.uploadLift(uploadEvent);
                    outputQueue.put(result);
                }
            }else{
                while (!queue.isEmpty()) {
                    UploadEvent uploadEvent = queue.take();
                    Integer result = recordUploadClient.uploadLift(uploadEvent);
                    outputQueue.put(result);

                }
            }
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
    }
}
