package skiclient;

import io.swagger.client.ApiClient;
import io.swagger.client.api.SkiersApi;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

/**
 * Multi-thread uploader to upload random events generated by EventGenerator to the server
 */
public class RecordUploader extends Thread {
    private RecordUploadClient recordUploadClient;
    private BlockingQueue<UploadEvent> queue;
    private BlockingQueue<Integer> outputQueue;
    private int limit;

    public RecordUploader(RecordUploadClient recordUploadClient,
                          BlockingQueue<UploadEvent> queue,
                          int limit,
                          BlockingQueue<Integer> outputQueue) {
        this.recordUploadClient = recordUploadClient;
        this.queue = queue;
        this.limit = limit;
        this.outputQueue = outputQueue;
    }

    @Override
    public void run() {
        try {
            if (limit > 0) {
                for (int i = 0; i < limit; i++) {
                    UploadEvent uploadEvent = queue.take();
                    // TODO: Uncomment the following line if want to see the result in progress
                    // Comment it since print will severely slow the program
                    //System.out.println("Uploading event: " + uploadEvent.toString());
                    Integer result = recordUploadClient.uploadLift(uploadEvent);
                    outputQueue.put(result);
                }
            } else {
                while (!queue.isEmpty()) {
                    UploadEvent uploadEvent = queue.take();
                    Integer result = recordUploadClient.uploadLift(uploadEvent);
                    outputQueue.put(result);
                }
            }
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
    }
}
